# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 08:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EduPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_year', models.CharField(max_length=100, verbose_name='\u5b66\u5e74')),
                ('term_type', models.CharField(max_length=100, verbose_name='\u5b66\u671f')),
                ('province_name', models.CharField(blank=True, max_length=100, verbose_name='\u7701')),
                ('city_name', models.CharField(blank=True, max_length=100, verbose_name='\u5e02')),
                ('country_name', models.CharField(blank=True, max_length=100, verbose_name='\u53bf')),
                ('town_name', models.CharField(blank=True, max_length=100, verbose_name='\u4e61\u9547\u8857\u9053')),
                ('point_name', models.CharField(max_length=100, verbose_name='\u6559\u5b66\u70b9\u540d\u79f0')),
                ('number', models.IntegerField(default=1, verbose_name='\u6559\u5ba4\u7ec8\u7aef\u6570\u91cf')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65e5\u671f')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65e5\u671f')),
                ('remark', models.CharField(blank=True, max_length=255, verbose_name='\u5907\u6ce8')),
            ],
        ),
        migrations.CreateModel(
            name='EduPointDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[(b'moon', '\u536b\u661f\u7ec8\u7aef'), (b'room', '\u6559\u5b66\u70b9\u6559\u5ba4')], max_length=20, verbose_name='\u7ec8\u7aef\u7c7b\u578b')),
                ('name', models.CharField(max_length=20, verbose_name='\u6559\u5ba4\u7ec8\u7aef\u7f16\u53f7')),
                ('communicate_key', models.CharField(blank=True, max_length=100, verbose_name='\u540c\u6b65\u5bc6\u94a5')),
                ('cpuID', models.CharField(blank=True, max_length=100, verbose_name='\u7ed1\u5b9acpuID')),
                ('last_active_time', models.DateTimeField(blank=True, null=True, verbose_name='\u8fde\u63a5\u670d\u52a1\u5668\u65f6\u95f4')),
                ('last_upload_time', models.DateTimeField(blank=True, null=True, verbose_name='\u6570\u636e\u540c\u6b65\u65f6\u95f4')),
                ('edupoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu_point.EduPoint')),
            ],
        ),
        migrations.CreateModel(
            name='EduPointDetailDesktopViewLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_year', models.CharField(max_length=100, verbose_name='\u5b66\u5e74')),
                ('term_type', models.CharField(max_length=100, verbose_name='\u5b66\u671f')),
                ('province_name', models.CharField(blank=True, max_length=100, verbose_name='\u7701')),
                ('city_name', models.CharField(blank=True, max_length=100, verbose_name='\u5e02')),
                ('country_name', models.CharField(blank=True, max_length=100, verbose_name='\u53bf')),
                ('town_name', models.CharField(blank=True, max_length=100, verbose_name='\u4e61\u9547\u8857\u9053')),
                ('point_name', models.CharField(max_length=100, verbose_name='\u6559\u5b66\u70b9\u540d\u79f0')),
                ('number', models.CharField(max_length=100, verbose_name='\u6559\u5b66\u70b9\u6559\u5ba4\u7f16\u53f7')),
                ('create_time', models.DateTimeField(blank=True, null=True, verbose_name='\u56fe\u7247\u521b\u5efa\u65e5\u671f')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='\u6dfb\u52a0\u65e5\u671f')),
                ('pic', models.CharField(blank=True, max_length=255, verbose_name='\u7f51\u7edcURL')),
                ('host', models.CharField(blank=True, max_length=255, verbose_name='\u7f51\u7edcURL\u57df\u540d')),
                ('edupoint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='edu_point.EduPoint')),
                ('edupointdetail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='edu_point.EduPointDetail')),
            ],
        ),
        migrations.CreateModel(
            name='EduPointMachineTimeUsed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_year', models.CharField(max_length=100, verbose_name='\u5b66\u5e74')),
                ('term_type', models.CharField(max_length=100, verbose_name='\u5b66\u671f')),
                ('province_name', models.CharField(blank=True, max_length=100, verbose_name='\u7701')),
                ('city_name', models.CharField(blank=True, max_length=100, verbose_name='\u5e02')),
                ('country_name', models.CharField(blank=True, max_length=100, verbose_name='\u53bf')),
                ('town_name', models.CharField(blank=True, max_length=100, verbose_name='\u4e61\u9547\u8857\u9053')),
                ('point_name', models.CharField(max_length=100, verbose_name='\u6559\u5b66\u70b9\u540d\u79f0')),
                ('number', models.CharField(max_length=100, verbose_name='\u6559\u5b66\u70b9\u6559\u5ba4\u7f16\u53f7')),
                ('create_time', models.DateField(auto_now_add=True, verbose_name='\u521b\u5efa\u65e5\u671f')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='\u6700\u540e\u66f4\u65b0\u65f6\u95f4')),
                ('use_time', models.IntegerField(default=0, verbose_name='\u4f7f\u7528\u65f6\u957f(\u5206\u949f)')),
                ('boot_time', models.IntegerField(default=0, verbose_name='\u5f00\u673a\u65f6\u957f(\u5206\u949f)')),
                ('boot_count', models.IntegerField(default=0, verbose_name='\u5f00\u673a\u6b21\u6570')),
                ('edupoint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='edu_point.EduPoint')),
                ('edupointdetail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='edu_point.EduPointDetail')),
            ],
        ),
        migrations.CreateModel(
            name='EduPointResourceCatalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalog', models.CharField(max_length=255, verbose_name='\u6559\u5b66\u70b9\u8d44\u6e90\u63a5\u6536\u76ee\u5f55')),
                ('edupoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu_point.EduPoint')),
            ],
        ),
        migrations.CreateModel(
            name='EduPointResourceReceLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_year', models.CharField(max_length=100, verbose_name='\u5b66\u5e74')),
                ('term_type', models.CharField(max_length=100, verbose_name='\u5b66\u671f')),
                ('province_name', models.CharField(blank=True, max_length=100, verbose_name='\u7701')),
                ('city_name', models.CharField(blank=True, max_length=100, verbose_name='\u5e02')),
                ('country_name', models.CharField(blank=True, max_length=100, verbose_name='\u53bf')),
                ('town_name', models.CharField(blank=True, max_length=100, verbose_name='\u4e61\u9547\u8857\u9053')),
                ('point_name', models.CharField(max_length=100, verbose_name='\u6559\u5b66\u70b9\u540d\u79f0')),
                ('rece_time', models.DateField(blank=True, null=True, verbose_name='\u8d44\u6e90\u63a5\u6536\u65f6\u95f4')),
                ('rece_count', models.BigIntegerField(default=0, verbose_name='\u8d44\u6e90\u63a5\u6536\u6587\u4ef6\u603b\u4e2a\u6570')),
                ('rece_size', models.BigIntegerField(default=0, verbose_name='\u8d44\u6e90\u63a5\u6536\u6587\u4ef6\u603b\u5927\u5c0f')),
                ('rece_type', models.BigIntegerField(default=0, verbose_name='\u8d44\u6e90\u63a5\u6536\u7c7b\u578b\u603b\u6570\u91cf')),
                ('edupoint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='edu_point.EduPoint')),
            ],
        ),
        migrations.CreateModel(
            name='EduPointResourceReceLogDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, verbose_name='\u8d44\u6e90\u7c7b\u578b')),
                ('size', models.BigIntegerField(verbose_name='\u8be5\u8d44\u6e90\u7c7b\u578b\u62e5\u6709\u6587\u4ef6\u5927\u5c0f')),
                ('count', models.BigIntegerField(verbose_name='\u8be5\u8d44\u6e90\u7c7b\u578b\u62e5\u6709\u6587\u4ef6\u6570\u91cf')),
                ('edu_point_resource_rece_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu_point.EduPointResourceReceLog')),
            ],
        ),
    ]
