# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 08:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BigIntSyncID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100, verbose_name='App label')),
                ('model', models.CharField(max_length=100, verbose_name='Model name')),
                ('sync_id', models.IntegerField(default=0, verbose_name='Next use id')),
            ],
        ),
        migrations.CreateModel(
            name='MachineTimeUsed',
            fields=[
                ('uuid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('term_school_year', models.CharField(blank=True, max_length=20, verbose_name='\u5b66\u5e74')),
                ('term_type', models.CharField(blank=True, max_length=20, verbose_name='\u5b66\u671f')),
                ('province_name', models.CharField(blank=True, max_length=100, verbose_name='\u7701')),
                ('city_name', models.CharField(blank=True, max_length=100, verbose_name='\u5e02')),
                ('country_name', models.CharField(blank=True, max_length=100, verbose_name='\u533a\u53bf')),
                ('town_name', models.CharField(blank=True, max_length=100, verbose_name='\u8857\u9053')),
                ('school_name', models.CharField(blank=True, max_length=100, verbose_name='\u5b66\u6821')),
                ('grade_name', models.CharField(blank=True, max_length=20, verbose_name='\u5e74\u7ea7')),
                ('class_name', models.CharField(blank=True, max_length=20, verbose_name='\u73ed\u7ea7')),
                ('mac', models.CharField(blank=True, max_length=20, verbose_name='MAC')),
                ('create_time', models.DateTimeField(blank=True, verbose_name='\u5f00\u59cb\u4f7f\u7528\u65e5\u671f')),
                ('use_time', models.IntegerField(default=0, verbose_name='\u5f00\u673a\u65f6\u957f(\u5206\u949f)')),
                ('use_count', models.IntegerField(default=0, verbose_name='\u5f00\u673a\u6b21\u6570')),
                ('school', models.ForeignKey(blank=True, db_column=b'school_uuid', null=True, on_delete=django.db.models.deletion.CASCADE, to='db.Group')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='bigintsyncid',
            unique_together=set([('app_label', 'model')]),
        ),
        migrations.AlterIndexTogether(
            name='machinetimeused',
            index_together=set([('term_school_year', 'term_type', 'town_name', 'school_name', 'grade_name', 'class_name'), ('create_time', 'town_name', 'school_name', 'grade_name', 'class_name')]),
        ),
    ]
